# From https://github.com/docker/awesome-compose/tree/master/react-express-mysql
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    working_dir: /code
    command: node src/index.js
    ports:
      - 80:80
      - 9229:9229
      - 9230:9230
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpw
      - DB_NAME=raydb
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: raydb
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: