# NOTE: This is to setup an environment for Jenkins to run in.
FROM node:20

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    apt-get update && apt-get install -y unzip && \
    unzip awscliv2.zip && ./aws/install && \
    rm -rf awscliv2.zip aws/

WORKDIR /app
